2024-04-14 15:58:15 INFO [32m pytest tests/backend/test_create_project.py::TestProjectCreateWithInvalidData::test_create_project_with_invalid_ids[Roles.PROJECT_VIEWER-\u04487727192] (setup)[0m
curl -X GET 'http://localhost:8111/authenticationTest.html?csrf' \
-H 'User-Agent: python-requests/2.31.0'\
-H 'Accept-Encoding: gzip, deflate'\
-H 'Accept: */*'\
-H 'Connection: keep-alive'\
-H 'Authorization: Basic OjEyOTQ0MTg2MjIwMjc0MjA1MjI=' \
-d ''
2024-04-14 15:58:15 INFO [32m pytest tests/backend/test_create_project.py::TestProjectCreateWithInvalidData::test_create_project_with_invalid_ids[Roles.PROJECT_VIEWER-\u04487727192][0m
curl -X POST 'http://localhost:8111/app/rest/projects' \
-H 'User-Agent: python-requests/2.31.0'\
-H 'Accept-Encoding: gzip, deflate'\
-H 'Accept: application/json'\
-H 'Connection: keep-alive'\
-H 'Content-Type: application/json'\
-H 'X-TC-CSRF-Token: 448116e6-1d13-48cc-a478-44cf5c9a0f4d'\
-H 'Cookie: RecentLogin=; TCSESSIONID=2C517E19DE9FE8158DB34408E83C0497'\
-H 'Content-Length: 116'\
-H 'Authorization: Basic OjEyOTQ0MTg2MjIwMjc0MjA1MjI=' \
-d '{"parentProject": {"locator": "_Root"}, "name": "section", "id": "\u04487727192", "copeAllAssociatedSettings": true}' 

2024-04-14 15:58:15 INFO 	RESPONSE:
STATUS_CODE: [31m500[0m
DATA: [31mError has occurred during request processing, status code: 500 (Internal Server Error).
Details: jetbrains.buildServer.serverSide.InvalidIdentifierException: Project ID "Ã‘Âˆ7727192" is invalid: contains non-latin letter 'Ã‘Âˆ'. ID should start with a latin letter and contain only latin letters, digits and underscores (at most 225 characters).
Error occurred while processing this request.[0m