2024-04-14 15:58:16 INFO [32m pytest tests/backend/test_create_project.py::TestProjectCreateWithInvalidData::test_create_project_with_invalid_parentProject[Roles.PROJECT_DEVELOPER-_Root4] (setup)[0m
curl -X GET 'http://localhost:8111/authenticationTest.html?csrf' \
-H 'User-Agent: python-requests/2.31.0'\
-H 'Accept-Encoding: gzip, deflate'\
-H 'Accept: */*'\
-H 'Connection: keep-alive'\
-H 'Authorization: Basic OjEyOTQ0MTg2MjIwMjc0MjA1MjI=' \
-d ''
2024-04-14 15:58:16 INFO [32m pytest tests/backend/test_create_project.py::TestProjectCreateWithInvalidData::test_create_project_with_invalid_parentProject[Roles.PROJECT_DEVELOPER-_Root4][0m
curl -X POST 'http://localhost:8111/app/rest/projects' \
-H 'User-Agent: python-requests/2.31.0'\
-H 'Accept-Encoding: gzip, deflate'\
-H 'Accept: application/json'\
-H 'Connection: keep-alive'\
-H 'Content-Type: application/json'\
-H 'X-TC-CSRF-Token: 09df97df-abf0-4f64-88e6-b298bb06690b'\
-H 'Cookie: RecentLogin=; TCSESSIONID=53C2C73BB87947D8D95EF476BAB8E206'\
-H 'Content-Length: 111'\
-H 'Authorization: Basic OjEyOTQ0MTg2MjIwMjc0MjA1MjI=' \
-d '{"parentProject": {"locator": "_Root4"}, "name": "can", "id": "ellb9_cgeQz", "copeAllAssociatedSettings": true}' 

2024-04-14 15:58:16 INFO 	RESPONSE:
STATUS_CODE: [31m404[0m
DATA: [31mResponding with error, status code: 404 (Not Found).
Details: jetbrains.buildServer.server.rest.errors.NotFoundException: No project found by name or internal/external id '_Root4'.
Could not find the entity requested. Check the reference is correct and the user has permissions to access the entity.[0m