2024-04-02 20:36:57 INFO [32m pytest tests/backend/test_create_project.py::TestProjectCreateWithInvalidData::test_create_project_with_invalid_ids[Roles.PROJECT_ADMIN-\u04514861388] (setup)[0m
curl -X GET 'http://localhost:8111/authenticationTest.html?csrf' \
-H 'User-Agent: python-requests/2.31.0'\
-H 'Accept-Encoding: gzip, deflate'\
-H 'Accept: */*'\
-H 'Connection: keep-alive'\
-H 'Authorization: Basic OjQwOTU3ODkyMzU3NzU2NDM0OTc=' \
-d ''
2024-04-02 20:36:57 INFO [32m pytest tests/backend/test_create_project.py::TestProjectCreateWithInvalidData::test_create_project_with_invalid_ids[Roles.PROJECT_ADMIN-\u04514861388][0m
curl -X POST 'http://localhost:8111/app/rest/projects' \
-H 'User-Agent: python-requests/2.31.0'\
-H 'Accept-Encoding: gzip, deflate'\
-H 'Accept: application/json'\
-H 'Connection: keep-alive'\
-H 'Content-Type: application/json'\
-H 'X-TC-CSRF-Token: eeddb6f5-081f-489e-8667-21b8ee0b5037'\
-H 'Cookie: RecentLogin=; TCSESSIONID=377E6ED679C96ACDA4B1DD9B22B261C7'\
-H 'Content-Length: 113'\
-H 'Authorization: Basic OjQwOTU3ODkyMzU3NzU2NDM0OTc=' \
-d '{"parentProject": {"locator": "_Root"}, "name": "true", "id": "\u04514861388", "copeAllAssociatedSettings": true}' 

2024-04-02 20:36:57 INFO 	RESPONSE:
STATUS_CODE: [31m500[0m
DATA: [31mError has occurred during request processing, status code: 500 (Internal Server Error).
Details: jetbrains.buildServer.serverSide.InvalidIdentifierException: Project ID "Ã‘Â‘4861388" is invalid: contains non-latin letter 'Ã‘Â‘'. ID should start with a latin letter and contain only latin letters, digits and underscores (at most 225 characters).
Error occurred while processing this request.[0m