2024-04-04 12:41:23 INFO [32m pytest tests/backend/test_create_project.py::TestProjectCreateWithInvalidData::test_create_project_with_invalid_ids[Roles.PROJECT_DEVELOPER-9572jhBUgWr] (setup)[0m
curl -X GET 'http://localhost:8111/authenticationTest.html?csrf' \
-H 'User-Agent: python-requests/2.31.0'\
-H 'Accept-Encoding: gzip, deflate'\
-H 'Accept: */*'\
-H 'Connection: keep-alive'\
-H 'Authorization: Basic OjM4NzAyODQzODA0MjQ1NTUzMTM=' \
-d ''
2024-04-04 12:41:23 INFO [32m pytest tests/backend/test_create_project.py::TestProjectCreateWithInvalidData::test_create_project_with_invalid_ids[Roles.PROJECT_DEVELOPER-9572jhBUgWr][0m
curl -X POST 'http://localhost:8111/app/rest/projects' \
-H 'User-Agent: python-requests/2.31.0'\
-H 'Accept-Encoding: gzip, deflate'\
-H 'Accept: application/json'\
-H 'Connection: keep-alive'\
-H 'Content-Type: application/json'\
-H 'X-TC-CSRF-Token: 07dd50fb-1b1c-42d2-a21c-d84668cd53e2'\
-H 'Cookie: RecentLogin=; TCSESSIONID=16FC7C5BBF21E675C733A05B4668A84D'\
-H 'Content-Length: 111'\
-H 'Authorization: Basic OjM4NzAyODQzODA0MjQ1NTUzMTM=' \
-d '{"parentProject": {"locator": "_Root"}, "name": "able", "id": "9572jhBUgWr", "copeAllAssociatedSettings": true}' 

2024-04-04 12:41:23 INFO 	RESPONSE:
STATUS_CODE: [31m500[0m
DATA: [31mError has occurred during request processing, status code: 500 (Internal Server Error).
Details: jetbrains.buildServer.serverSide.InvalidIdentifierException: Project ID "9572jhBUgWr" is invalid: starts with non-letter character '9'. ID should start with a latin letter and contain only latin letters, digits and underscores (at most 225 characters).
Error occurred while processing this request.[0m