2024-04-04 11:22:08 INFO [32m pytest tests/backend/test_create_project.py::TestProjectCreateWithInvalidData::test_create_project_with_invalid_ids[Roles.PROJECT_ADMIN-\u044b3049584] (setup)[0m
curl -X GET 'http://localhost:8111/authenticationTest.html?csrf' \
-H 'User-Agent: python-requests/2.31.0'\
-H 'Accept-Encoding: gzip, deflate'\
-H 'Accept: */*'\
-H 'Connection: keep-alive'\
-H 'Authorization: Basic OjM3NTgwODc3MjcwMTQ1NDE3MTU=' \
-d ''
2024-04-04 11:22:08 INFO [32m pytest tests/backend/test_create_project.py::TestProjectCreateWithInvalidData::test_create_project_with_invalid_ids[Roles.PROJECT_ADMIN-\u044b3049584][0m
curl -X POST 'http://localhost:8111/app/rest/projects' \
-H 'User-Agent: python-requests/2.31.0'\
-H 'Accept-Encoding: gzip, deflate'\
-H 'Accept: application/json'\
-H 'Connection: keep-alive'\
-H 'Content-Type: application/json'\
-H 'X-TC-CSRF-Token: 2581bd25-9130-43ad-8138-ed855234ac1a'\
-H 'Cookie: RecentLogin=; TCSESSIONID=A5C5851918155194506AEAE7977A97A1'\
-H 'Content-Length: 114'\
-H 'Authorization: Basic OjM3NTgwODc3MjcwMTQ1NDE3MTU=' \
-d '{"parentProject": {"locator": "_Root"}, "name": "these", "id": "\u044b3049584", "copeAllAssociatedSettings": true}' 

2024-04-04 11:22:08 INFO 	RESPONSE:
STATUS_CODE: [31m500[0m
DATA: [31mError has occurred during request processing, status code: 500 (Internal Server Error).
Details: jetbrains.buildServer.serverSide.InvalidIdentifierException: Project ID "Ã‘Â‹3049584" is invalid: contains non-latin letter 'Ã‘Â‹'. ID should start with a latin letter and contain only latin letters, digits and underscores (at most 225 characters).
Error occurred while processing this request.[0m