2024-04-03 15:06:40 INFO [32m pytest tests/backend/test_create_project.py::TestProjectCreateWithInvalidData::test_create_project_with_invalid_parentProject[Roles.PROJECT_ADMIN-_Root ] (setup)[0m
curl -X GET 'http://localhost:8111/authenticationTest.html?csrf' \
-H 'User-Agent: python-requests/2.31.0'\
-H 'Accept-Encoding: gzip, deflate'\
-H 'Accept: */*'\
-H 'Connection: keep-alive'\
-H 'Authorization: Basic OjQ0OTMwMjgxMDEzMzk2NTMzODk=' \
-d ''
2024-04-03 15:06:40 INFO [32m pytest tests/backend/test_create_project.py::TestProjectCreateWithInvalidData::test_create_project_with_invalid_parentProject[Roles.PROJECT_ADMIN-_Root ][0m
curl -X POST 'http://localhost:8111/app/rest/projects' \
-H 'User-Agent: python-requests/2.31.0'\
-H 'Accept-Encoding: gzip, deflate'\
-H 'Accept: application/json'\
-H 'Connection: keep-alive'\
-H 'Content-Type: application/json'\
-H 'X-TC-CSRF-Token: d5b84895-0251-4b75-bae4-fe94a7639a83'\
-H 'Cookie: RecentLogin=; TCSESSIONID=8AEE0324B97B8D1A39F5FAF31A5383F0'\
-H 'Content-Length: 111'\
-H 'Authorization: Basic OjQ0OTMwMjgxMDEzMzk2NTMzODk=' \
-d '{"parentProject": {"locator": "_Root "}, "name": "buy", "id": "T024ah79mPt", "copeAllAssociatedSettings": true}' 

2024-04-03 15:06:40 INFO 	RESPONSE:
STATUS_CODE: [31m404[0m
DATA: [31mResponding with error, status code: 404 (Not Found).
Details: jetbrains.buildServer.server.rest.errors.NotFoundException: No project found by name or internal/external id '_Root '.
Could not find the entity requested. Check the reference is correct and the user has permissions to access the entity.[0m