2024-03-31 20:54:22 INFO [32m pytest tests/backend/test_create_project.py::TestProjectCreateWithInvalidData::test_create_project_with_invalid_ids[Roles.PROJECT_ADMIN-\u04458576409] (setup)[0m
curl -X GET 'http://localhost:8111/authenticationTest.html?csrf' \
-H 'User-Agent: python-requests/2.31.0'\
-H 'Accept-Encoding: gzip, deflate'\
-H 'Accept: */*'\
-H 'Connection: keep-alive'\
-H 'Authorization: Basic OjE2OTcxMTQxODIxOTA0NjI4NjA=' \
-d ''
2024-03-31 20:54:22 INFO [32m pytest tests/backend/test_create_project.py::TestProjectCreateWithInvalidData::test_create_project_with_invalid_ids[Roles.PROJECT_ADMIN-\u04458576409][0m
curl -X POST 'http://localhost:8111/app/rest/projects' \
-H 'User-Agent: python-requests/2.31.0'\
-H 'Accept-Encoding: gzip, deflate'\
-H 'Accept: application/json'\
-H 'Connection: keep-alive'\
-H 'Content-Type: application/json'\
-H 'X-TC-CSRF-Token: 46696836-0255-4596-85dd-68dd55fb9c0d'\
-H 'Cookie: RecentLogin=; TCSESSIONID=06FBA78F8D0D4F468D7385B52AA38953'\
-H 'Content-Length: 115'\
-H 'Authorization: Basic OjE2OTcxMTQxODIxOTA0NjI4NjA=' \
-d '{"parentProject": {"locator": "_Root"}, "name": "social", "id": "\u04458576409", "copeAllAssociatedSettings": true}' 

2024-03-31 20:54:22 INFO 	RESPONSE:
STATUS_CODE: [31m500[0m
DATA: [31mError has occurred during request processing, status code: 500 (Internal Server Error).
Details: jetbrains.buildServer.serverSide.InvalidIdentifierException: Project ID "Ã‘Â…8576409" is invalid: contains non-latin letter 'Ã‘Â…'. ID should start with a latin letter and contain only latin letters, digits and underscores (at most 225 characters).
Error occurred while processing this request.[0m