2024-03-31 20:54:22 INFO [32m pytest tests/backend/test_create_project.py::TestProjectCreateWithInvalidData::test_create_project_with_invalid_parentProject[Roles.PROJECT_ADMIN- Root] (setup)[0m
curl -X GET 'http://localhost:8111/authenticationTest.html?csrf' \
-H 'User-Agent: python-requests/2.31.0'\
-H 'Accept-Encoding: gzip, deflate'\
-H 'Accept: */*'\
-H 'Connection: keep-alive'\
-H 'Authorization: Basic OjE2OTcxMTQxODIxOTA0NjI4NjA=' \
-d ''
2024-03-31 20:54:22 INFO [32m pytest tests/backend/test_create_project.py::TestProjectCreateWithInvalidData::test_create_project_with_invalid_parentProject[Roles.PROJECT_ADMIN- Root][0m
curl -X POST 'http://localhost:8111/app/rest/projects' \
-H 'User-Agent: python-requests/2.31.0'\
-H 'Accept-Encoding: gzip, deflate'\
-H 'Accept: application/json'\
-H 'Connection: keep-alive'\
-H 'Content-Type: application/json'\
-H 'X-TC-CSRF-Token: dfbc77af-7a4f-45c6-9973-f32804dbfab4'\
-H 'Cookie: RecentLogin=; TCSESSIONID=EC93FC005B22C7B0BA8D487720A1D62A'\
-H 'Content-Length: 112'\
-H 'Authorization: Basic OjE2OTcxMTQxODIxOTA0NjI4NjA=' \
-d '{"parentProject": {"locator": " Root"}, "name": "apply", "id": "xQv65F4ha_A", "copeAllAssociatedSettings": true}' 

2024-03-31 20:54:22 INFO 	RESPONSE:
STATUS_CODE: [31m404[0m
DATA: [31mResponding with error, status code: 404 (Not Found).
Details: jetbrains.buildServer.server.rest.errors.NotFoundException: No project found by name or internal/external id ' Root'.
Could not find the entity requested. Check the reference is correct and the user has permissions to access the entity.[0m